### PR TITLE
Remove the confidentiality banner at the top

### PR DESCRIPTION
**Pull request by eris-webserv**
One line fix :D

### CODE REVIEW

**Comment by eris-webserv** [comment]
Do not merge, the button broke by removing it??? stadia what

**Comment by eris-webserv** [comment]
nevermind, somehow I missed a part of it. >:(

**Comment by luigimannoni** [comment]
Thanks, just request a review when you're happy with it :)

**Comment by eris-webserv** [comment]
I WAS JUST ABOUT TO SAY I AM DONE. (For good this time.)

**Pull request merged**
