### PR TITLE
Implemented PKG for binary packaging Node16 on x86 for win, linux and mac

### PR DESCRIPTION
**Pull request by kwuite**
SSL-serve does not have the right api. Moved to serve-static lib which is also better maintained; start with bin.js and package with npm run pkg

### CODE REVIEW

**Comment by kwuite** [comment]
Done:
- Compile to binary with PKG
- Upload assets to a release tag with github action
- Tested on Linux and Windows

Flashtest: 
- Works on Windows 10 Pro
- Linux has Udev issues - might be out of scope.
- Mac has not been tested.

Out of scope:
- Test script: simulation not possible

**Comment by luigimannoni** [comment]
I'll try a test flash as soon I am able to.

I have taken for granted that SSL was needed to access connected devices, does it also works on http?

**Comment by kwuite** [comment]
**SSL**

It is possible to add SSL support if we need this. However I am unsure how this affects system compatibility because the certificates will be self-signed.

**Flashtest 1**
OS: Ubuntu 22.04.1 LTS
Version 108.0.5359.98 (Official Build) (64-bit)

I am going through the process to flash the firmware with the binary version.

In the first step I see the chrome browser can find the device:
image

Connecting is also allowed:
image

Unlocking:
image

Since I am on Ubuntu, I can pair with the device but after this step I need to execute terminal commands in order to be able to continue with the process:

- You need to manually edit a rules file on your computer to allow Chrome to access Stadia Controllers over USB.
  - NotAllowedError: Failed to open the device.
  - https://support.google.com/stadia/answer/13067284?visit_id=638099068583350800-735422458&p=controllerconnect&rd=1#linuxrule&zippy=%2Cim-on-a-linux-based-computer-and-cant-update-my-stadia-controller-help

image

**Linux/Udev**

- I could check if UDEV rules are in place before starting the binary version on Linux
- Request sudo access to update UDEV with the appropriate rules or display the adjustments to the user so they can execute it by themselves
- Is this even necesarry for Linux based user.
- Maybe only focus on mac and windows for the binary?

I will switch to my Windows OS and validate the .exe to see if I face any issues.

**Comment by kwuite** [comment]
**Flashtest 2**

OS: Windows 10 pro
Chome Version  108.0.5359.126 (Officiële build) (64-bits)

1. Starting the binary opened a CMD prompt with the message "service started at..."
2. NodeJS security request as expected
image
3. I encountered a directory issues with the binary and resolved this on my windows machine
image
4. I disabled my internet/wifi and continued with the flash step. It said it successfully flashed my controller (without an internet connection)
image

After the above flashing process I connected the stadia controller with ease to my Samsung Galaxy note 22.

**Note:** I did receive an error that I needed an app to work with the stadia controller but I pressed the up and down button and it instantly responded on my phone. I could navigate through my Android with the buttons on my controller.

**Comment by kwuite** [comment]
@luigimannoni I hope this PR helps with running your code completely locally. I have tried to keep it as simple as possible. Let me know if there is anything else I can do for this PR.

**Comment by luigimannoni** [comment]
Looks good to me - triggered also a release with your compiled binaries. Big thanks!

**Pull request merged**
